[package]
name = "hello_world_android_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
egui = "0.21.0"
egui-winit = "0.21.1"
egui_wgpu_backend = "0.22.0"
epi = "0.17.0"
egui_winit_platform = "0.18.0"
chrono = "0.4"
pollster = "0.3.0"
wgpu = "0.15.1"
tracing-subscriber = "0.3"
egui_demo_lib = "0.21.0"
log = "*"

[target.'cfg(debug_assertions)'.dependencies]
simple_logger = "*"
android_logger = "0.13.0"

# This dependency will only be included when not targeting Android
[target.'cfg(not(target_os = "android"))'.dependencies]
winit = { version="0.28" }

# This dependency will only be included when targeting Android
[target.'cfg(target_os = "android")'.dependencies]
winit = { version="0.28", default-features = false, features = ["android-native-activity"] }