[package]
name = "hello_world_android_egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
egui = "0.19.0"
egui-winit = "0.19.0"
egui_wgpu_backend = "0.20.0"
epi = "0.17.0"
egui_winit_platform = {path = "/home/inferno/.dev/egui_winit_platform"}
chrono = "0.4"
pollster = "0.2"
winit = { git="https://github.com/rust-windowing/winit.git" , features = ["android-native-activity"] }
#winit = "0.27.1"
wgpu = "0.14.0"
tracing-subscriber = "0.3"
egui_demo_lib = "0.19"

# This dependency will only be included when targeting Android
[target.'cfg(target_os = "android")'.dependencies]
#ndk-glue = "0.7.0" # Substitute this with the latest ndk-glue version you wish to use